#!/bin/sh

set -eu

append_coauthors() {
    COMMIT_MSG_FILE=$1

    if grep -q -i -e "Co-authored-by" "$COMMIT_MSG_FILE"; then
      echo 'Co-author already supplied'
    else
      tmpfile="$COMMIT_MSG_FILE"-temp
      sed -e '/^Co-authored-by/d' $COMMIT_MSG_FILE >"$tmpfile"
      mv "$tmpfile" "$COMMIT_MSG_FILE"

      git-pair print >>"$COMMIT_MSG_FILE"
      print_coauthors
    fi
}

print_coauthors() {
    echo 'Committing with co-authors:'
    OLDIFS="$IFS"
    IFS='
'
    for AUTHOR in $(git-pair show)
    do
        printf " + $AUTHOR\n"
    done
    IFS="$OLDIFS"
}

append_coauthors $1
